version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  # Reduce frequency of alerts about reference files?
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
