version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Reduce frequency of alerts about reference files?
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "monthly"
